// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5bw5nF45zPiRCWc5tiENCGe4vor1ttkQ',
    appId: '1:502441549708:web:53fb9fb6e763459f7b80a9',
    messagingSenderId: '502441549708',
    projectId: 'fir-d16de',
    authDomain: 'fir-d16de.firebaseapp.com',
    storageBucket: 'fir-d16de.firebasestorage.app',
    measurementId: 'G-VQW3Q68M8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJLbgV2FmtXpb1yOfDRTzk-T2tG4p0bc',
    appId: '1:502441549708:android:31e7de8291ca21fd7b80a9',
    messagingSenderId: '502441549708',
    projectId: 'fir-d16de',
    storageBucket: 'fir-d16de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVnbIq5xWt2oeCGF9Tk7d6xzdDeadOA8Y',
    appId: '1:502441549708:ios:7e59dc10fdee520a7b80a9',
    messagingSenderId: '502441549708',
    projectId: 'fir-d16de',
    storageBucket: 'fir-d16de.firebasestorage.app',
    iosBundleId: 'com.example.firebaseInti',
  );
}
